### ISSUE TITLE
老哥好，想问一下使用方法

### ISSUE THREAD

**Issue by ypq123456789** [lee-cq/alist-sync#5]
目前咱们前两种是怎么使用呢？
我现在是使用本地rclone同步的，上传的带宽，太感人了。不知道老哥调用actions上传的带宽怎么样？

**Comment by saxiaoju** [comment]
大佬，求一下使用方法，alist配置文件是怎么引用的？摸索半天不懂🙃，非常感谢！

**Comment by lee-cq** [comment]
你好啊，

该项目目前还在开发阶段，还有一些BUG在调试，请谨慎使用。

Github Action 上次测试 OneDrive ->  139pan 速度在30MB/s左右。

后面有时间我会出配置方式（目前我在重构代码）。

非常感谢你对该项目的支持。

**Comment by lee-cq** [comment]
@saxiaoju 使用RCLone相关流程能简单介绍下吗？ 

也许在该项目可用前可以封装一个RClone版本的Action，来解决速度问题。

**Comment by ypq123456789** [comment]
> @saxiaoju 使用RCLone相关流程能简单介绍下吗？
> 
> 也许在该项目可用前可以封装一个RClone版本的Action，来解决速度问题。

老哥好，我使用rclone与咱们这个项目无关哈，是通过reclone挂载alist webdav，然后从onedrive向阿里云盘的加密盘sync，不显示进度，但是看火绒的带宽基本上是很慢的，下载的进度可能只有10兆每秒，上传 也差不多，因为走加宽上限就卡那了

**Comment by user4396** [comment]
老哥你这咋用？我./bootstarp.sh install 后执行alist-sync copy -h http://localhost:5244 -u admin -p 123456 -s /1 -t /2 提示alist_sync命令未找到啊，咋用？

**Comment by ypq123456789** [comment]
> 老哥你这咋用？我./bootstarp.sh install 后执行alist-sync copy -h http://localhost:5244 -u admin -p 123456 -s /1 -t /2 提示alist_sync命令未找到啊，咋用？

等这个老哥出配置方法吧，自己琢磨估计不太行

**Comment by ypq123456789** [comment]
![2a121b22944940bb2db511d9a937292d](https://github.com/lee-cq/alist-sync/assets/114487221/ca6cf5d9-25fa-49f1-b244-ed48af051651)
用了老哥的配置方法，该配置的都配置了，报错这个

**Comment by lee-cq** [comment]
> ![2a121b22944940bb2db511d9a937292d](https://private-user-images.githubusercontent.com/114487221/309530992-ca6cf5d9-25fa-49f1-b244-ed48af051651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjM3NTIsIm5iZiI6MTcwOTUyMzQ1MiwicGF0aCI6Ii8xMTQ0ODcyMjEvMzA5NTMwOTkyLWNhNmNmNWQ5LTI1ZmEtNDlmMS1iMjQ0LWVkNDhhZjA1MTY1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwMzM3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjQ4ZGRmMDYxZjAyYjM2YTc0NDQzYmQ4NGI1YTdhMjNhYWQxZGE1NGZmNGY2ZTAzNDVhMDhiMjEyNzQ1MjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c8-TCDUJJtI1DUvt1bwoblofSQ7CUvSW-ncJxRIupbw) 用了老哥的配置方法，该配置的都配置了，报错这个

备份格式不对，ALIST_BACKUP_CONFIG的值应该是在alist网页端，通过备份得到的。

SYNC_CONFIG  和  ALIST_BACKUP_CONFIG注意区分

**Comment by ypq123456789** [comment]
> > ![2a121b22944940bb2db511d9a937292d](https://private-user-images.githubusercontent.com/114487221/309530992-ca6cf5d9-25fa-49f1-b244-ed48af051651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjM3NTIsIm5iZiI6MTcwOTUyMzQ1MiwicGF0aCI6Ii8xMTQ0ODcyMjEvMzA5NTMwOTkyLWNhNmNmNWQ5LTI1ZmEtNDlmMS1iMjQ0LWVkNDhhZjA1MTY1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwMzM3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjQ4ZGRmMDYxZjAyYjM2YTc0NDQzYmQ4NGI1YTdhMjNhYWQxZGE1NGZmNGY2ZTAzNDVhMDhiMjEyNzQ1MjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c8-TCDUJJtI1DUvt1bwoblofSQ7CUvSW-ncJxRIupbw) 用了老哥的配置方法，该配置的都配置了，报错这个
> 
> 备份格式不对，ALIST_BACKUP的值应该是在alist网页端，通过备份得到的。
> 
> SYNC_CONFIG 和 ALIST_BACKUP 注意区分

我记得我没弄反呀，我为了防止自己记错，重新弄了下这两个，没弄反，还是报这个错误
SYNC_CONFIG内容：
```
# 如果没有配置MongoDB，文档将会存储至本地缓存
mongodb_uri: "mongodb+srv://${username}:${password}@${host}/alist_sync?retryWrites=true&w=majority&appName=A1"

# 缓存文件夹
cache_dir: ./.alist-sync-cache

# 是否以Daemon模式运行
daemon: false

thread_pool_max_size:
  workers: 5
  scanner: 5
  checker: 5

# Alist 服务器信息 type: list
alist_servers:
  - base_url: http://loaclhost:5244/
    username: "admin"
    password: "123456"
    verify_ssl: false

  - base_url: http://remote_alist_server/
    username: "admin"
    password: "admin"


sync_groups:
  - name: "sync1"
    enable: true  # 默认值: True
    # 同步类型，一共4种：
    # 1 copy:如果目标目录中已经存在该文件，则跳过
    #        忽略存在与目标目录中但不存在于源目录中的文件
    # 2 mirror: 如果目标目录中已经存在该文件，则跳过
    #           删除存在于目录目录但不存在于源目录中的文件
    # 3 sync: 如果目标目录中已经存在该文件，则跳过
    #         删除存在于目录目录但不存在于源目录中的文件
    # 4 sync-incr: 基于文件的修改时间，只同步源目录中修改时间晚于目标目录的文件
    type: "copy"

    # 检查间隔，单位为秒，如果daemon为False，则该值无效
    interval: 300  # 默认值: 300 秒, 5 分钟

    # 是否需要备份，如果为True，则会在同步之前备份目标目录
    # 对于copy，该值无效
    need_backup: false  # 默认值: False

    # 备份目录，当need_backup为True时，该值有效
    # 一个相对目录，最终为每一个group中的每一个server创建一个备份目录
    backup_dir: "./.alist-sync-backup"  # 默认值: ./.alist-sync-backup

    # 黑名单，支持通配符, 使用 fnmatch.fnmatchcase 函数进行匹配
    # 详情参考标准库文档 https://docs.python.org/3/library/fnmatch.html
    # 后面可能会重构，以支持 Linux Glob 模式。
    # 其路径必须相对与Group中定义的目录，或者使用*开头
    # .alist-sync* 将自动添加到黑名单中
    # 例子：
    # 忽略 http://localhost:5244/test1/base/ 目录下的所有目录及文件： "base/*"
    # 忽略所有bfstm文件： "*.bfstm"
    blacklist:
      - "*.bfstm"
      - "base/*"
      - "testa/b/*"

    # 同步目录，一个完整的AList URL，
    # 对于copy, mirror 第一个为源目录，其他个为目标目录
    # Alist服务器信息需要提前在alist_servers中配置
    # 支持在不同的Alist服务器之间同步
    # 例子：http://localhost:5244/test1
    group:
      - "http://loaclhost:5244/OnedriveCF代理"
      - "http://loaclhost:5244/阿里云盘加密"

notify: # 通知服务，当触发一些异常后，将会发送通知。
  - enable: false
    type: email
    smtp_host: ""
    smtp_port: 25
    sender: ""
    password: ""
    recipients:
      - ""

  - enable: false
    type: webhook
    webhook_url: ""
    headers:
      K: V

logs:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: ./logs/alist-sync.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
      encoding: utf8

  loggers:
    alist-sync:
      level: DEBUG
      handlers:
        - console
        - file

    alist-sdk:
      level: INFO
      handlers:
        - console
        - file
```

ALIST_BACKUP复制的这个txt里面的内容
![1709527706022](https://github.com/lee-cq/alist-sync/assets/114487221/23663e44-60e5-440f-a0d8-3775a810bc8e)

password和username也设置了
![1709527735563](https://github.com/lee-cq/alist-sync/assets/114487221/e75dc3d5-4c6d-4dfa-8243-6bed7d6082f1)
